# Config file for automatic testing at travis-ci.org

dist: trusty
language: python
python:
    - 3.6
sudo: false

cache:
  directories:
    - $HOME/.pip-accel
    - $HOME/.cache/pip

env:
  matrix:
    - TOXENV=py27-django18
#    - TOXENV=py27-django19
#    - TOXENV=py27-django110
    - TOXENV=py35-django18
#    - TOXENV=py35-django19
#    - TOXENV=py35-django110
    - TOXENV=py36-django18
#    - TOXENV=py36-django19
#    - TOXENV=py36-django110

matrix:
  fast_finish: true

before_install:
  # work around https://github.com/travis-ci/travis-ci/issues/8363
  - pyenv global system 3.5

install:
    - pip install --upgrade pip
    - travis_retry make dev_install

script:
    - pip freeze
    - travis_retry make tox

after_success:
    # https://github.com/codecov/codecov-bash
    - bash <(curl -s https://codecov.io/bash)
