# Config file for automatic testing at travis-ci.org

dist: trusty
language: python
python:
    - 3.6
sudo: false

cache:
  directories:
    - $HOME/.pip-accel
    - $HOME/.cache/pip

env:
  matrix:
    - TOXENV=py27-django18
#    - TOXENV=py27-django19
#    - TOXENV=py27-django110
    - TOXENV=py35-django18
#    - TOXENV=py35-django19
#    - TOXENV=py35-django110
    - TOXENV=py36-django18
#    - TOXENV=py36-django19
#    - TOXENV=py36-django110

matrix:
  fast_finish: true

install:
    - travis_retry make dev_install

script:
    - pip freeze
    - travis_retry make tox


