# Config file for automatic testing at travis-ci.org

sudo: required
dist: trusty
# https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
group: deprecated-2017Q4
language: python

cache:
  directories:
    - $HOME/.pip-accel
    - $HOME/.cache/pip

matrix:
    fast_finish: true
    include:
        # see output from: `tox -l`
        -   env: TOXENV=py35-django18
            python: 3.5
        -   env: TOXENV=py35-django111
            python: 3.5

        -   env: TOXENV=py36-django18
            python: 3.6
        -   env: TOXENV=py36-django111
            python: 3.6

        -   env: TOXENV=pypy-django18
            python: pypy
        -   env: TOXENV=pypy-django111
            python: pypy

install:
    - pip install --upgrade pip
    - travis_retry make dev_install

script:
    - pip freeze
    - travis_retry make tox

after_success:
    # https://github.com/codecov/codecov-bash
    - bash <(curl -s https://codecov.io/bash)

