# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 09:05
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_landing_page', '0001_squashed_0003_auto_20180219_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagemodeltranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='plugin_landing_page.LandingPageModel'),
        ),
    ]
