# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpagemodel',
            options={'default_permissions': ('add', 'change', 'delete', 'can_publish'), 'ordering': ('-createtime',), 'verbose_name': 'Landing Page', 'verbose_name_plural': 'Landing Pages'},
        ),
        migrations.AlterModelOptions(
            name='landingpagemodeltranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Landing Page Translation'},
        ),
    ]
