# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_landing_page', '0002_auto_20180219_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpagemodel',
            options={'default_permissions': ('add', 'change', 'delete', 'can_publish'), 'ordering': ('-createtime',), 'verbose_name': 'Landing Page', 'verbose_name_plural': 'Landing Pages'},
        ),
    ]
