# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('plugin_anchor_menu', '0001_initial'), ('plugin_anchor_menu', '0002_dropdownanchormenupluginmodel')]

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugin_anchor_menu_anchorpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DropDownAnchorMenuPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugin_anchor_menu_dropdownanchormenupluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('menu_id', models.SlugField(default='anchor_menu', max_length=254, verbose_name='The internal menu ID')),
                ('link_type', models.CharField(choices=[('h', "Add '#anchor' to browser addess."), ('s', "Don't add '#anchor' to browser addess.")], default='s', max_length=1, verbose_name='Link type')),
                ('first_label', models.CharField(blank=True, default='Please select', help_text='Label for the first option. (The first anchor will be used, if empty)', max_length=254, null=True, verbose_name='First label')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
